### ISSUE TITLE
Fehler unter Contao 4.4

### ISSUE THREAD

**Issue by 9teufel** [fritzmg/contao-newslist-extended#1]
Habe das Modul unter Contao 4.4 laufen, im News-Listenmodul wird mir die neue Option auch angezeigt. Jedoch wird der Link nicht übernommen.

Beispiel:
Weiterleitungsseite definiert im Newsarchiv: (news/test/popup/)
Weiterleitungsseite definiert im Modul: (news/test/detail/)

Im Frontend ausgegeben wird jedoch immer die URL auf der das Listenmodul liegt (in meinem Fall: news/test/eintrag). Es macht auch keinen Unterschied wenn ich eine andere Weiterleitungsseite im Modul definiere, die URL bleibt immer news/test/eintrag/ statt news/test/detail/eintrag.

**Comment by fritzmg** [comment]
Ha... tatsächlich hat dieses feature nie funktioniert, in egal welcher Contao Version 😁 

In `1.1.3` sollt es nun passen.

**Comment by fritzmg** [comment]
Bzw. in `1.1.4` ist es nun komplett gefixed...
