### ISSUE TITLE
Problem mit der Übergabe des Titles an $objTemplate->more 

### ISSUE THREAD

**Issue by Mediaquery** [fritzmg/contao-newslist-extended#2]
Unter Contao 4.4.43 wird bei aktivierter Weiterleitungsseite innerhalb der Newslist an den p.more Link kein Titel übergeben. Die Globalvariable $GLOBALS['TL_LANG']['MSC']['more'] wird geschrieben danach bleibt die Ausgabe jedoch leer.

**Comment by fritzmg** [comment]
Fixed in 8a823bb and released as `1.1.6`.
