### ISSUE TITLE
Contao 4.9 Weiterleitungsseite überschreiben

### ISSUE THREAD

**Issue by 9teufel** [fritzmg/contao-newslist-extended#3]
Habe die Erweiterung unter 4.9 (nach Update) im Einsatz.

Weiterleitungsseite überschreiben scheint hier nicht mehr zu funktionieren. Trotz definierter Weiterleitungsseite im Modul wird die Weiterleitungsseite aus dem Archiv verwendet.

Und:
Im Modul habe ich die Auswahl des Nachrichtenleser doppelt, wäre schön wenn der Eintrag ab > 4.7 nicht mehr angezeigt wird. 

Contao 4.9 und die Erweiterung sind am Letztstand.

Danke!

**Comment by 9teufel** [comment]
Ich merke gerade der Standard-Link im Template `<?= $this->more ?>` führt zur richtigen Weiterleitungsseite.

In meinem Template verwende ich jedoch `<a href="<?php echo $this->link; ?>">` und damit scheint es nicht mehr zu laufen.

Mit `<?= $this->link ?>` passt der Link.

Der Link der beim Bild hinterlegt ist `<?php $this->insert('image', $this->arrData); ?>` geht auch auf die Archiv Weiterleitungsseite.

**Comment by fritzmg** [comment]
> Im Modul habe ich die Auswahl des Nachrichtenleser doppelt, wäre schön wenn der Eintrag ab > 4.7 nicht mehr angezeigt wird.

This is now fixed in version `1.1.7`.

**Comment by fritzmg** [comment]
> Der Link der beim Bild hinterlegt ist `<?php $this->insert('image', $this->arrData); ?>` geht auch auf die Archiv Weiterleitungsseite.

This is now fixed in version `1.1.8`.

**Comment by fritzmg** [comment]
> Ich merke gerade der Standard-Link im Template `<?= $this->more ?>` führt zur richtigen Weiterleitungsseite.
> 
> In meinem Template verwende ich jedoch `<a href="<?php echo $this->link; ?>">` und damit scheint es nicht mehr zu laufen.
> 
> Mit `<?= $this->link ?>` passt der Link.

I was unable to reproduce any issues there. `$this->more`, `$this->link` and `$this->linkHeadline` contain the correct link with the target page override taken into account:

https://github.com/fritzmg/contao-newslist-extended/blob/89715d3768a1105aba9816935e5d0d31255abe10/system/modules/newslist_extended/classes/NewslistExtended.php#L101-L103

**Comment by 9teufel** [comment]
Wow, danke für die schnelle Fehlerkorrektur!

> > Ich merke gerade der Standard-Link im Template `<?= $this->more ?>` führt zur richtigen Weiterleitungsseite.
> > In meinem Template verwende ich jedoch `<a href="<?php echo $this->link; ?>">` und damit scheint es nicht mehr zu laufen.
> > Mit `<?= $this->link ?>` passt der Link.
> 
> I was unable to reproduce any issues there. `$this->more`, `$this->link` and `$this->linkHeadline` contain the correct link with the target page override taken into account:

Ja, stimmt, das passt bei mir jetzt auch. Hatte da wohl eine falsche Seite im Cache.

**Comment by fritzmg** [comment]
> Wow, danke für die schnelle Fehlerkorrektur!

No problem 😃. If you use a lot of extensions from fritzmg/ or inspiredminds/, consider sponsoring on GitHub :)
