### ISSUE TITLE
Newslist Extended causes HTTP 500 error (Contao 4.11.5)

### ISSUE THREAD

**Issue by RWesemann** [fritzmg/contao-newslist-extended#4]
When I install "Newslist Extended" on a plain Contao instance (V. 4.11.5), the installation runs through without any problems. Afterwards, however, an HTTP 500 error appears on all Contao pages (backend, frontend, install tool). When I uninstall the extension, everything works again without problems.

There are no entries in the log.

**Comment by fritzmg** [comment]
I am unable to reproduce the issue. I have installed the extension in a Contao 4.11.5 instance and was able to access the front and back end as well as the install tool. Check your web server's log for errors (or your PHP error log).

**Comment by RWesemann** [comment]
Thank you for the quick response. I'll check it over the next few days.

**Comment by RWesemann** [comment]
Okay, I have now reinstalled everything again and now I can't reproduce the error either. I did not have any logs enabled on the web server that I could check. Now that it works, I assume the error was somewhere on my side. Sorry for the trouble.
