### ISSUE TITLE
newsarchive extended

### ISSUE THREAD

**Issue by andre5tz** [fritzmg/contao-newslist-extended#5]
Hallo,

ich suche gerade nach der Möglichkeit, auch für das Modul Nachrichtenarchiv die Weiterleitungsseite zu überschreiben. Wäre es möglich, die Funktion noch mit aufzunehmen?

Bin mir nicht sicher, ob ich was übersehen habe, wäre dann ja auch eigentlich newsarchiv-extended.

VG
André

**Comment by fritzmg** [comment]
Done in b5f236e. Please consider sponsoring to keep packages like these maintained :)
