### ISSUE TITLE
canonical tag uses malformed uri

### ISSUE THREAD

**Issue by ctwbg** [fritzmg/contao-newslist-extended#6]
When using a multi-domain installation the generated canonical tag uses a malformed href that generates a 404 error when checking/crawling the website.

Domains Setup Example:
- main.domain.com
- sub.domain.com

Generated canonical tag on sub.domain.com:
https://sub.domain.com///main.domain.com/news/view/news-item-123

This may be an issue specific to my installation, but I have no way to verify that.

--

Contao 4.13.6 (use canonical is turned off for all domains)
Newslist Extended 1.3.1
.htaccess - rewrites all URLs to https

**Comment by fritzmg** [comment]
Can you please test if `dev-master` fixes your issue?

**Comment by fritzmg** [comment]
Although for Contao 4.13 I will probably need to make additional adjustments, otherwise you might end up with 2 canonical URLs :)

// edit: done in ddcf4d5

**Comment by ctwbg** [comment]
Sadly, it does not work even after installing _dev-master_.

I have created a blank Contao installation with only newslist-extended installed and I can reproduce the error, so it should not be an issue specific to my main installation.

I have tested with and without _generate canonical_ settings enabled for each page root, no difference.

**Comment by fritzmg** [comment]
At the moment I am unable to reproduce your issue. From your description it looks like Contao is generating a news URL that looks like this:

```
//main.domain.com/news/view/news-item-123
```

But that should never be the case. It should always either be relative or absolute including the scheme (`http:` or `https:`).

**Comment by ctwbg** [comment]
Your hint gave me an idea, and it may have something to do with the protocol settings in the page root ("URL-Einstellungen -> Protokoll").

When I switch the page root to "http://" the correct canonical url is used...

Maybe Contao generates protocol-relative urls when using https - and you check for the protocol when building the canonical tag?

**Comment by fritzmg** [comment]
> Maybe Contao generates protocol-relative urls when using https

That would be a bug in Contao then. It is supposed to always generate either:

* Absolute URLs including protocol.
* Path absolute URLs.
* Relative URLs.

Never protocol relative URLs.
