### ISSUE TITLE
Need assistance with disabling image links for highlighted items

### ISSUE THREAD

**Issue by Webstylerin** [fritzmg/contao-newslist-extended#7]
Hello,

I am currently using your extension to set different image sizes for news items, and that works perfectly. However, I need to disable the image links. I have implemented the following code in the template to achieve this:

```
<?php if ($this->addImage): ?>
    <?php $this->href=""; ?>
    <?php $this->insert('image', $this->arrData); ?>
<?php endif; ?>
```

Despite this, the links remain active for highlighted items. Could you please guide me on how to effectively remove the image links for highlighted news items using your extension? I am using Contao 5.3 for this setup.

Thank you for your help!

Best regards,
Nicole

**Comment by fritzmg** [comment]
This has nothing to do with this extension. Please post in the Contao community forum or the community slack.
